// Generated by CoffeeScript 1.6.3
var socket;

socket = io.connect('http://localhost:2222');

socket.on('message', function(msg) {
  var container, div;
  container = $('div.messages');
  div = $('<div>');
  div.html(msg.date + " - " + msg.content);
  return container.prepend(div);
});
