// Generated by CoffeeScript 1.6.3
var io;

io = require('socket.io').listen(2222);

io.sockets.on('connection', function(socket) {
  var rabbitHub, subHub;
  rabbitHub = require('rabbitmq-nodejs-client');
  subHub = rabbitHub.create({
    task: 'sub',
    channel: 'rabbit-node-test'
  });
  subHub.on('connection', function(hub) {
    return hub.on('message', function(msg) {
      return socket.emit('message', {
        date: new Date(),
        content: msg
      });
    });
  });
  subHub.connect();
  return socket.on('disconnect', function() {
    io.sockets.emit('user disconnected');
    return subHub.end();
  });
});
